sonar.projectKey=palcarazm_bootstrap5-toggle
sonar.organization=palcarazm
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.coverage.exclusions=docs/**,src/test/**
sonar.cpd.exclusions=src/test/**